# Generated by Django 6.0.6 on 2026-06-03 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Especies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mascotas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chip", models.CharField(max_length=120)),
                ("peso_kg", models.IntegerField()),
                ("edad", models.CharField(max_length=20, unique=True)),
                ("estado_vacunada", models.BooleanField(default=True)),
                (
                    "nombre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mascotas",
                        to="petcare.especies",
                    ),
                ),
            ],
        ),
    ]
